import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import Footer from './Footer'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Haneen Khan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-stone-50 ${openSans.className}`}>
        <main className="max-w-[1200px] px-6 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
