import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import Footer from './Footer'
import Header from './Header'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Haneen Khan | Sex & Intimacy Coach',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-stone-50 ${openSans.className}`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
